apiVersion: v1
kind: Service
metadata:
  name: ruby
spec:
  ports:
  - port: 9292
    targetPort: 9292
  type: LoadBalancer
  selector:
    app: ruby
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruby
spec:
  replicas: 0
  selector:
    matchLabels:
      app: ruby
  template:
    metadata:
      labels:
        app: ruby
        app.kubernetes.io/utility-pod-origin: 'true'
    spec:
      containers:
      - name: ruby
        image: ruby-example
        command: ["bundle", "exec", "puma"]
        ports:
        - containerPort: 9292
        env:
          - name: RACK_ENV
            value: "development"
